name: Release Manifest
description: Release installation manifest (reusable for both candidate and production)

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  custom_tag_prefix:
    description: 'Custom tag prefix for manifest'
    required: false
    default: ''
  manifest_output:
    description: 'Output filename for manifest (if not provided, defaults to testing.yaml or manifest.yaml based on calling workflow)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod

    - name: Get tensorleap chart version
      id: get_tensorleap_chart_version
      run: |
        CHART_VERSION=$(cat charts/tensorleap/Chart.yaml | grep -E '^version:' | awk '{print $2}')
        echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get tensorleap infra chart version
      id: get_tensorleap_infra_chart_version
      run: |
        INFRA_CHART_VERSION=$(cat charts/tensorleap-infra/Chart.yaml | grep -E '^version:' | awk '{print $2}')
        echo "version=$INFRA_CHART_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set manifest output filename
      id: set_manifest_output
      run: |
        # If manifest_output is explicitly provided, use it
        if [ -n "${{ inputs.manifest_output }}" ]; then
          MANIFEST_FILE="${{ inputs.manifest_output }}"
        else
          # If called from release_production.yml, use "manifest.yaml", otherwise use "testing.yaml"
          if [ "${{ github.workflow }}" == "Release Version To Production" ]; then
            MANIFEST_FILE="manifest.yaml"
          else
            MANIFEST_FILE="testing.yaml"
          fi
        fi
        echo "filename=$MANIFEST_FILE" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set manifest version
      id: set_manifest_version
      run: |
        # Set the manifest version to the tensorleap chart version (as-is, no suffix removal)
        CUSTOM_PREFIX="${{ inputs.custom_tag_prefix }}"
        if [ -z "$CUSTOM_PREFIX" ]; then
          # If called from release_production.yml, use "manifest", otherwise use "testing"
          if [ "${{ github.workflow }}" == "Release Version To Production" ]; then
            CUSTOM_PREFIX="manifest"
          else
            CUSTOM_PREFIX="testing"
          fi
        fi
        TAG="${CUSTOM_PREFIX}-${{ steps.get_tensorleap_chart_version.outputs.version }}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        # Only mark as latest if tag starts with "manifest-"
        if [[ "$TAG" == manifest-* ]]; then
          echo "make_latest=true" >> $GITHUB_OUTPUT
        else
          echo "make_latest=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Create installation manifest
      run: |
        go run . create-manifest --tensorleap-chart-version ${{ steps.get_tensorleap_chart_version.outputs.version }} --tensorleap-infra-chart-version ${{ steps.get_tensorleap_infra_chart_version.outputs.version }} --tag ${{ steps.set_manifest_version.outputs.tag }} --output ${{ steps.set_manifest_output.outputs.filename }}
      shell: bash

    - name: Print charts versions
      run: |
        echo "Tensorleap chart version: ${{ steps.get_tensorleap_chart_version.outputs.version }}"
        echo "Tensorleap infra chart version: ${{ steps.get_tensorleap_infra_chart_version.outputs.version }}"
      shell: bash

    - name: Print manifest
      run: cat ${{ steps.set_manifest_output.outputs.filename }}
      shell: bash

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.set_manifest_output.outputs.filename }}
        tag: "${{ steps.set_manifest_version.outputs.tag }}"
        makeLatest: ${{ steps.set_manifest_version.outputs.make_latest }}
        skipIfReleaseExists: true
        generateReleaseNotes: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
