image_tag: master-8342c78e
image: public.ecr.aws/tensorleap/node-server
disableDatadogMetrics: false
enableKeycloak: true
installedServerVersion: "unknown"

ingress:
  enabled: true

mongodb:
  enabled: true
  connectionString: mongodb://mongodb/tensorleap?tls=false&ssl=false

localBucketPath: ""

mongodb_image: docker.io/library/mongo:6.0.5
