name: Install Server
description: Install Tensorleap server using leap-cli

inputs:
  tag:
    description: 'Manifest tag to install (e.g., manifest-1.4.95)'
    required: true

runs:
  using: composite
  steps:
    - name: Install leap-cli
      run: |
        curl -s https://raw.githubusercontent.com/tensorleap/leap-cli/master/install.sh | bash
      shell: bash

    - name: Install Tensorleap server
      run: |
        leap server install -t ${{ inputs.tag }}
        if [ $? -ne 0 ]; then
          echo "❌ Installation failed"
          exit 1
        fi
        echo "✅ Installation completed successfully"
      shell: bash