{{ if .Values.global.elasticsearch.enabled }}
{{ if and .Values.global.create_local_volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /var/lib/tensorleap/standalone/storage/elasticsearch
    type: DirectoryOrCreate
  claimRef:
    name: elasticsearch-master-elasticsearch-master-0
    namespace: {{ .Release.Namespace }}
{{ end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-master-elasticsearch-master-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{ if .Values.global.create_local_volumes }}
  volumeName: elasticsearch-data
{{ else if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
{{ end }}
{{ end }}
