apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /var/lib/tensorleap/standalone/storage/elasticsearch
    type: DirectoryOrCreate
  claimRef:
    name: elasticsearch-master-elasticsearch-master-0
    namespace: {{ .Release.Namespace }}
