apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
data:
  # External hostname / path (uses your Helm value env_name)
  KC_HOSTNAME_URL: "{{ .Values.global.url }}/auth"
  KC_HOSTNAME_ADMIN_URL: "{{ .Values.global.url }}/auth"

  # Runtime / proxy
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_PROXY: "edge"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "{{ .Values.global.tls.enabled | toString }}"

  # Cache / DB (your current choices)
  KC_DB: "dev-file"
  KC_CACHE: "local"
  KC_CACHE_STACK: ""
