apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/lib/tensorleap/standalone/storage/minio
    type: DirectoryOrCreate
  claimRef:
    name: tensorleap-minio
    namespace: {{ .Release.Namespace }}
