apiVersion: v1
kind: Service
metadata:
  name: tensorleap-minio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
  selector:
    app: minio
    release: tensorleap
