apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 0
globalDefault: false
description: "This priority class should be used for infra services only"

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority
value: -500
globalDefault: false
description: "This priority class should be used for engine jobs"

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: -1000
globalDefault: false
description: "This priority class should be used for the engine helpers"

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: warmup-priority
value: -1500
globalDefault: false
description: "This priority class should be used for the engine helpers"

