apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: docker.io/library/rabbitmq:3.9.22
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - rabbitmqctl
                  - stop_app
          env:
            - name: RABBITMQ_ERL_COOKIE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: erlangCookie
            - name: RABBITMQ_DATA_DIR
              value: /var/lib/rabbitmq
            - name: RABBITMQ_MNESIA_BASE
              value: /var/lib/rabbitmq/mnesia
            - name: RABBITMQ_LOG_BASE
              value: /var/log/rabbitmq
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
            exec:
              command:
                - rabbitmq-diagnostics
                - status
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 20
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            items:
              - key: enabled_plugins
                path: enabled_plugins
              - key: rabbitmq.conf
                path: rabbitmq.conf
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
        labels:
          app: rabbitmq
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
