apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    log.file.level = debug
    log.console = true
    log.console.level = debug
  erlangCookie: 3e3abae2-6325-11ec-90d6-0242ac120003
