eck-operator:
  managedNamespaces:
    - tensorleap

nvidiaGpu:
  enabled: false
  visibleDevices: "all"

registry:
  enabled: true
  image: "ghcr.io/project-zot/zot-linux-amd64:v2.1.15"
  sync:
    enabled: true
    registries: []

global:
  elasticsearch:
    enabled: true
