apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: engine-jobs-cleanup
  labels:
    cleanupJob: "true"
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: engine-jobs-cleanup
              image: gcr.io/tensorleap/tensorleap-ops
              args:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  kubectl get jobs --selector engineJob=true -o json | \
                    jq -r '.items[]
                          | select(.status.succeeded > 0 )
                          | select(.status.completionTime | fromdateiso8601 < now - 90*60)
                          | .metadata.name' | \
                    xargs -I JOBNAME kubectl delete jobs/JOBNAME

                  kubectl get jobs --selector cleanupJob=true -o json | \
                    jq -r '.items[]
                          | select(.status.succeeded > 0 )
                          | select(.status.completionTime | fromdateiso8601 < now - 90*60)
                          | .metadata.name' | \
                    xargs -I JOBNAME kubectl delete jobs/JOBNAME
          restartPolicy: OnFailure
