{{ if .Values.gpu }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-template-gpu-cm
data:
  job: |
    metadata:
      labels:
        engineJob: "true"
        suffix: k80
    spec:
      ttlSecondsAfterFinished: 36000 # 10 hours
      template:
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/tensorleap/main/engine:{{ .Values.image_tag }}
              name: engine
              resources:
                limits:
                  nvidia.com/gpu: 1
              env:
                - name: JOB_PAYLOAD
              envFrom:
                - configMapRef:
                    name: engine-cm
              volumeMounts:
{{ if .Values.localDataDirectory }}
                - name: local-user-data
                  mountPath: {{ .Values.localDataDirectory }}
{{ end }}
          restartPolicy: Never
{{ if .Values.schedulerName }}
          schedulerName: {{ .Values.schedulerName }}
{{ end }}
          volumes:
{{ if .Values.localDataDirectory }}
            - name: local-user-data
              hostPath:
                path: {{ .Values.localDataDirectory }}
                type: DirectoryOrCreate
{{ end }}
{{ end }}
