apiVersion: batch/v1
kind: CronJob
metadata:
  name: engine-jobs-cleanup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jobs-cleanup
          containers:
            - name: engine-jobs-cleanup
              image: docker.io/alpine/k8s:1.19.16
              args:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  kubectl get jobs --selector engineJob=true -o json | \
                    jq -r '.items[]
                          | select(.status | .succeeded > 0 or .faild > 0 )
                          | .metadata.name' | \
                    xargs -P0 -I JOBNAME kubectl delete jobs/JOBNAME
          restartPolicy: OnFailure
