apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-cm
data:
  PY_CONFIG: /app/config/config.yaml
  ELASTIC_HOST: http://elasticsearch-master:9200
  SESSION_BUCKET: session
  RABBIT_HOST: rabbitmq-headless
  RABBIT_USER: user
  RABBIT_PASSWORD: 3e3abae2-6325-11ec-90d6-0242ac120003
  FEEDBACK_TOPIC: feedback
  SUBSCRIBER_TOPIC: job-control-channel
  STORAGE_PROVIDER: minio
  STORAGE_ENDPOINT: tensorleap-minio
  STORAGE_PORT: "9000"
  CONTENT_BASE_URL: /session/
