apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-template-pysvcs-cm
data:
  job: |
    metadata:
      labels:
        engineJob: "true"
        suffix: svcs
    spec:
      ttlSecondsAfterFinished: 36000 # 10 hours
      template:
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/tensorleap/main/engine:{{ .Values.image_tag }}
              name: engine
              env:
                - name: JOB_PAYLOAD
              envFrom:
                - configMapRef:
                    name: engine-cm
              volumeMounts:
                - name: engine-pvc
                  mountPath: /nfs/
{{ if .Values.localDataDirectory }}
                - name: local-user-data
                  mountPath: {{ .Values.localDataDirectory }}
{{ end }}
          restartPolicy: Never
          volumes:
            - name: engine-pvc
              hostPath:
                path: /engine-data
                type: DirectoryOrCreate
{{ if .Values.localDataDirectory }}
            - name: local-user-data
              hostPath:
                path: {{ .Values.localDataDirectory }}
                type: DirectoryOrCreate
{{ end }}
