{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tensorleap-web-ui
  labels:
    app: tensorleap-web-ui
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: tensorleap-web-ui
      port:
        name: http
{{ end }}
