apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: tensorleap
volumes:
  - volume: /var/lib/tensorleap/standalone:/var/lib/tensorleap/standalone
    nodeFilters:
      - server:*
  - volume: /var/lib/tensorleap/standalone/images:/var/lib/rancher/k3s/agent/images
    nodeFilters:
      - server:*
  - volume: /var/lib/tensorleap/standalone/manifests/tensorleap.yaml:/var/lib/rancher/k3s/server/manifests/tensorleap.yaml
    nodeFilters:
      - server:*
ports:
  - port: 4589:80
    nodeFilters:
      - server:*:direct
env:
  - envVar: all_proxy=${all_proxy}
    nodeFilters:
      - server:*
  - envVar: ALL_PROXY=${ALL_PROXY}
    nodeFilters:
      - server:*
  - envVar: http_proxy=${http_proxy}
    nodeFilters:
      - server:*
  - envVar: HTTP_PROXY=${HTTP_PROXY}
    nodeFilters:
      - server:*
  - envVar: https_proxy=${https_proxy}
    nodeFilters:
      - server:*
  - envVar: HTTPS_PROXY=${HTTPS_PROXY}
    nodeFilters:
      - server:*
  - envVar: no_proxy=${no_proxy}
    nodeFilters:
      - server:*
  - envVar: NO_PROXY=${NO_PROXY}
    nodeFilters:
      - server:*
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
