apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: tensorleap
image: rancher/k3s:v1.25.6-k3s1
volumes:
  - volume: /var/lib/tensorleap/standalone:/var/lib/tensorleap/standalone
    nodeFilters:
      - server:*
  - volume: /var/lib/tensorleap/standalone/manifests/tensorleap.yaml:/var/lib/rancher/k3s/server/manifests/tensorleap.yaml
    nodeFilters:
      - server:*
  - volume: $PWD/config/containerd.toml.tmpl:/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
    nodeFilters:
      - server:*
ports:
  - port: 4589:80
    nodeFilters:
      - server:*:direct
env:
  - envVar: all_proxy=${all_proxy}
    nodeFilters:
      - server:*
  - envVar: ALL_PROXY=${ALL_PROXY}
    nodeFilters:
      - server:*
  - envVar: http_proxy=${http_proxy}
    nodeFilters:
      - server:*
  - envVar: HTTP_PROXY=${HTTP_PROXY}
    nodeFilters:
      - server:*
  - envVar: https_proxy=${https_proxy}
    nodeFilters:
      - server:*
  - envVar: HTTPS_PROXY=${HTTPS_PROXY}
    nodeFilters:
      - server:*
  - envVar: no_proxy=${no_proxy}
    nodeFilters:
      - server:*
  - envVar: NO_PROXY=${NO_PROXY}
    nodeFilters:
      - server:*
registries:
  create:
    name: tensorleap-registry
    host: "0.0.0.0"
    hostPort: "5699"
    proxy:
      remoteURL: https://us-central1-docker.pkg.dev
    volumes:
      - /var/lib/tensorleap/standalone/registry:/var/lib/registry
  config: |
    mirrors:
      docker.io:
        endpoint:
          - http://tensorleap-registry:5000
        rewrite:
          "^(.*)": "tensorleap/main/$1"
      k8s.gcr.io:
        endpoint:
          - http://tensorleap-registry:5000
        rewrite:
          "^(.*)": "tensorleap/main/$1"
      gcr.io:
        endpoint:
          - http://tensorleap-registry:5000
        rewrite:
          "^(.*)": "tensorleap/main/$1"
      docker.elastic.co:
        endpoint:
          - http://tensorleap-registry:5000
        rewrite:
          "^(.*)": "tensorleap/main/$1"
      quay.io:
        endpoint:
          - http://tensorleap-registry:5000
        rewrite:
          "^(.*)": "tensorleap/main/$1"
      us-central1-docker.pkg.dev:
        endpoint:
          - http://tensorleap-registry:5000
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
