{{ if .Values.global.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-secret
data:
  tls.crt: {{ .Values.global.tls.cert | b64enc }}
  tls.key: {{ .Values.global.tls.key | b64enc }}
{{ end }}