name: Release Charts
description: Release Helm charts using chart-releaser-action

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  branch:
    description: 'Branch to checkout'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
        fetch-depth: 0
        persist-credentials: true
        ref: ${{ inputs.branch }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    # chart-releaser-action will:
    # 1. Package charts from this branch (charts/ folder)
    # 2. Create GitHub releases with the .tgz packages
    # 3. Update ONLY the index.yaml on the index branch (pages_branch)
    # This keeps the index branch clean with only Helm repo data
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: charts
        pages_branch: index
      env:
        CR_TOKEN: ${{ inputs.github_token }}