{{- if .Values.registry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "6h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "compat": ["docker2s2"]
      },
      "log": {
        "level": "info"
      },
      "extensions": {
        "sync": {
          "enable": {{ .Values.registry.sync.enabled }},
          "registries": {{ .Values.registry.sync.registries | toJson }}
        }
      }
    }
{{- end }}
