apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-config
data:
  defaultGpuType: {{ .Values.gpu | ternary "gpu" "cpu" }}
  defaultCpuType: cpu
  machineTypes: |
    - id: cpu
      displayName: CPU
      templateConfigMap: engine-job-template-pysvcs-cm
{{ if .Values.gpu }}
    - id: gpu
      displayName: GPU
      templateConfigMap: engine-job-template-gpu-cm
{{ end }}
