apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-manager
  namespace: tensorleap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tensorleap
  name: deployment-manager-role
rules:
  - apiGroups: ["apps", ""]
    resources: ["deployments", "pods"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: tensorleap
subjects:
  - kind: ServiceAccount
    name: deployment-manager
    namespace: tensorleap
roleRef:
  kind: Role
  name: deployment-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-manager-nodes
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-manager-nodes-binding
subjects:
  - kind: ServiceAccount
    name: deployment-manager
    namespace: tensorleap
roleRef:
  kind: ClusterRole
  name: deployment-manager-nodes
  apiGroup: rbac.authorization.k8s.io

