apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-config
data:
  defaultGenericBaseImage: py38
  genericBaseImages: |
    - id: py38
      displayName: Python 3.8
      image: {{ .Values.generic_calculator_image }}
      tag: {{ .Values.image_tag }}-py38
    - id: py39
      displayName: Python 3.9
      image: {{ .Values.generic_calculator_image }}
      tag: {{ .Values.image_tag }}-py39
    - id: py310
      displayName: Python 3.10
      image: {{ .Values.generic_calculator_image }}
      tag: {{ .Values.image_tag }}-py310
  defaultGpuType: {{ .Values.gpu | ternary "gpu" "cpu" }}
  defaultCpuType: cpu
  machineTypes: |
    - id: cpu
      displayName: CPU
      resources:
        requests:
          memory: "5Gi"
{{ if .Values.gpu }}
    - id: gpu
      displayName: GPU
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          memory: "5Gi"
{{ if .Values.gpuTolerations }}
      tolerations:
{{ toYaml .Values.gpuTolerations | indent 12 }}
{{ end }}
{{ end }}