apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-config
data:
  defaultGpuType: {{ .Values.gpu | ternary "gpu" "cpu" }}
  defaultCpuType: cpu
  machineTypes: |
    - id: cpu
      displayName: CPU
      resources:
        requests:
          memory: "5Gi"
{{ if .Values.gpu }}
    - id: gpu
      displayName: GPU
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          memory: "5Gi"
{{ if .Values.gpuTolerations }}
      tolerations:
{{ toYaml .Values.gpuTolerations | indent 12 }}
{{ end }}
{{ end }}