apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-template-cm
data:
  job: |
    metadata:
      labels:
        engineJob: "true"
        suffix: placeholder
    spec:
      ttlSecondsAfterFinished: 36000 # 10 hours
      backoffLimit: 0
      template:
        metadata:
          annotations:
            ad.datadoghq.com/engine.logs: '[{"source": "python", "service": "engine"}]'
        spec:
          serviceAccountName: deployment-manager
          priorityClassName: medium-priority
          initContainers:
            - name: image-dependencies-builder
              image: {{ .Values.dependencies_image_name }}:{{ .Values.dependencies_image_tag }}
              securityContext:
                runAsUser: 0  # Optional: Run as root
                privileged: true
              env:
                - name: IMAGE_TAG
                - name: DEPENDENCY_URL
                - name: BASE_IMAGE
                  value: {{ .Values.generic_calculator_image }}:{{ .Values.image_tag }}-{{ .Values.generic_py_ver }}
                - name: TARGET_REPO
                  value: {{ .Values.target_repo }}
                - name: LOG_DIR
                  value: /shared/logs
                - name: IS_K3D
                  value: "true"
              volumeMounts:
                - name: shared-logs
                  mountPath: /shared/logs
                - name: docker-storage
                  mountPath: /var/lib/docker
          containers:
            - image: {{ .Values.image_name }}:{{ .Values.image_tag }}
              name: engine
              env:
                - name: JOB_PAYLOAD
              envFrom:
                - configMapRef:
                    name: engine-cm
              volumeMounts:
                - name: minio
                  mountPath: /usr/minio
                - name: shared-logs
                  mountPath: /shared/logs
{{- range .Values.additional_pvcs }}
                - name: {{ .name  }}-vol
                  mountPath: {{ .mountPath }}
{{- end }}
{{ range $index, $dir := .Values.localDataDirectories }}
                - name: local-user-data-{{ $index }}
                  mountPath: {{ $dir }}
{{ end }}
          restartPolicy: Never
{{ if .Values.schedulerName }}
          schedulerName: {{ .Values.schedulerName }}
{{ end }}
          volumes:
            - name: minio
              persistentVolumeClaim:
                claimName: tensorleap-minio
            - name: shared-logs
              emptyDir: {}  # Define shared-logs volume
            - name: docker-storage
              persistentVolumeClaim:
                claimName: tensorleap-docker-storage
{{- range .Values.additional_pvcs }}
            - name: {{ .name  }}-vol
              persistentVolumeClaim:
                claimName: {{ .name }}
{{- end }}
{{ range $index, $dir := .Values.localDataDirectories }}
            - name: local-user-data-{{ $index }}
              hostPath:
                path: {{ $dir }}
                type: DirectoryOrCreate
{{ end }}
