apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-job-template-cm
data:
  job: |
    metadata:
      labels:
        engineJob: "true"
        suffix: placeholder
    spec:
      ttlSecondsAfterFinished: 36000 # 10 hours
      backoffLimit: 0
      template:
        spec:
          containers:
<<<<<<< HEAD
            - image: {{ .Values.image }}:{{ .Values.image_tag }}
=======
            - image: us-central1-docker.pkg.dev/tensorleap/main/engine:{{ .Values.image_tag }}
>>>>>>> e1eb8ed (generalize engine job template (#172))
              name: engine
              env:
                - name: JOB_PAYLOAD
              envFrom:
                - configMapRef:
                    name: engine-cm
              volumeMounts:
{{- range .Values.additional_pvcs }}
                - name: {{ .name  }}-vol
                  mountPath: {{ .mountPath }}
{{- end }}
{{ if .Values.localDataDirectory }}
                - name: local-user-data
                  mountPath: {{ .Values.localDataDirectory }}
{{ end }}
          restartPolicy: Never
{{ if .Values.schedulerName }}
          schedulerName: {{ .Values.schedulerName }}
{{ end }}
          volumes:
{{- range .Values.additional_pvcs }}
            - name: {{ .name  }}-vol
              persistentVolumeClaim:
                claimName: {{ .name }}
{{- end }}
{{ if .Values.localDataDirectory }}
            - name: local-user-data
              hostPath:
                path: {{ .Values.localDataDirectory }}
                type: DirectoryOrCreate
{{ end }}
