apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-warmup-job
data:
  job: |
    metadata:
        name: engine-warmup-job
        labels:
            warmup-job: "true"
            created-by: "node-server"
    spec:
        template:
            spec:
                containers:
                - name: engine-placeholder
                  image: us-central1-docker.pkg.dev/tensorleap/main/engine:{{ .Values.image_tag }}
                  command: ["bash"]
                  args: ["-c", "sleep $WARMUP_TIMEOUT_SEC"]
                  envFrom:
                  - configMapRef:
                      name: engine-placeholder-env-configmap
                  resources:
                    limits:
                      nvidia.com/gpu: "1"
                restartPolicy: Never
                priorityClassName: "warmup-priority"
                nodeSelector: warmup-nodeSelector
                tolerations: warmup-tolerations
