{{ if .Values.global.create_local_volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pippin-docker-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/lib/tensorleap/standalone/storage/docker-storage
    type: DirectoryOrCreate
  claimRef:
    name: tensorleap-docker-storage
    namespace: {{ .Release.Namespace }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorleap-docker-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ if .Values.global.create_local_volumes }}
  volumeName: pippin-docker-data
{{ else if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
{{ end}}
