apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: 25Gi
            limits:
              memory: 25Gi
          image: docker.io/library/redis:latest
          ports:
          - containerPort: 6379
