apiVersion: v1
kind: Service
metadata:
  labels:
    app: tensorleap-web-ui
  name: tensorleap-web-ui
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: tensorleap-web-ui
  sessionAffinity: None
  type: ClusterIP
