ingress:
  enabled: true

ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      default-ssl-certificate: tensorleap/tls-secret
    image:
      digest: ""
    config:
      enable-snippets: "true"
      allow-snippet-annotations: "true"
    admissionWebhooks:
      patch:
        image:
          digest: ""

global:
  target_namespace: ""
  storageClassName: ""
  create_local_volumes: true
  disable_auth: false
  domain: "localhost"
  basePath: ""
  url: "http://localhost"
  proxyUrl: ""
  tls:
    enabled: false
    cert: ""
    key: ""

  elasticsearch:
    enabled: true
    url: ""

  keycloakx:
    enabled: true

keycloakx:
  enabled: true
  replicas: 1
  cache:
    stack: custom # <— IMPORTANT

  command: ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers=xforwarded"]

  extraEnvFrom: |
    - configMapRef:
        name: keycloak-env

  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
  fullnameOverride: keycloak
  ingress:
    enabled: false
  # make sure the container can write the volume (image runs as uid 1000)
  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  extraVolumes: |
    - name: keycloak-data
      persistentVolumeClaim:
        claimName: keycloak-data

  extraVolumeMounts: |
    - name: keycloak-data
      mountPath: /opt/keycloak/data
datadog:
  enabled: true
  clusterAgent:
    enabled: false
  datadog:
    processAgent:
      enabled: false
    tags:
      - "env:on-prem"
    logs:
      enabled: true
      containerCollectAll: false
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    site: datadoghq.com
