ingress:
  enabled: true

ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      default-ssl-certificate: tensorleap/tls-secret
    image:
      digest: ""
    config:
      enable-snippets: "true"
      allow-snippet-annotations: "true"
    admissionWebhooks:
      patch:
        image:
          digest: ""

global:
  target_namespace: ""
  storageClassName: ""
  create_local_volumes: true
  disable_auth: false
  domain: "localhost"
  basePath: ""
  url: "http://localhost"
  proxyUrl: ""
  tls:
    enabled: false
    cert: ""
    key: ""

  elasticsearch:
    enabled: true
    url: ""

  keycloakx:
    enabled: true

keycloakx:
  enabled: true
  replicas: 1
  command: ["/opt/keycloak/bin/kc.sh", "start"]
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: KC_DB
      value: dev-file
    - name: KC_PROXY
      value: "edge"
    - name: KC_HTTP_RELATIVE_PATH
      value: /auth
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_CACHE
      value: "local"
  fullnameOverride: keycloak
  ingress:
    enabled: false
  persistence:
    enabled: true
    existingClaim: "keycloak-data"
    size: 8Gi
    storageClass: "local-path"
    mountPath: /opt/keycloak/data # covers /opt/keycloak/data/h2
datadog:
  enabled: true
  clusterAgent:
    enabled: false
  datadog:
    processAgent:
      enabled: false
    tags:
      - "env:on-prem"
    logs:
      enabled: true
      containerCollectAll: false
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    site: datadoghq.com
