ingress:
  enabled: true

ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      default-ssl-certificate: tensorleap/tls-secret
    image:
      digest: ""
    config:
      enable-snippets: "true"
      allow-snippet-annotations: "true"
    admissionWebhooks:
      patch:
        image:
          digest: ""

global:
  postgresql:
    auth:
      existingSecret: keycloak-postgresql-secret
      password: keycloak123 # <-- Required for upgrade
      postgresPassword: pgrootpassword # <-- Optional, for superuser if needed
  target_namespace: ""
  storageClassName: ""
  create_local_volumes: true
  domain: "localhost"
  basePath: ""
  url: "http://localhost"
  proxyUrl: ""
  tls:
    enabled: false
    cert: ""
    key: ""

  elasticsearch:
    enabled: true
    url: ""

keycloak:
  replicas: 1
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin123

  fullnameOverride: keycloak
  ingress:
    enabled: false

  postgresql:
    enabled: true
    fullnameOverride: "keycloak-postgresql"
    auth:
      existingSecret: keycloak-postgresql-secret # ✅ Reference to secret
      username: keycloak
      database: keycloak
    primary:
      persistence:
        enabled: true
        existingClaim: "keycloak-postgresql-data"

datadog:
  enabled: true
  clusterAgent:
    enabled: false
  datadog:
    processAgent:
      enabled: false
    tags:
      - "env:on-prem"
    logs:
      enabled: true
      containerCollectAll: false
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    site: datadoghq.com
