ingress:
  enabled: true

ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx

minio:
  mode: standalone
  existingSecret: minio-secret
  service:
    type: NodePort
  securityContext:
    enabled: false
  persistence:
    size: 2Gi
    VolumeName: minio-data
  resources:
    requests:
      memory: 500Mi

global:
  target_namespace: ''
