ingress:
  enabled: true

ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      default-ssl-certificate: tensorleap/tls-secret
    image:
      digest: ''
    admissionWebhooks:
      patch:
        image:
          digest: ''

global:
  target_namespace: ''
  storageClassName: ''
  create_local_volumes: true
  domain: 'localhost'
  url: 'http://localhost'
  tls:
    enabled: false
    cert: ''
    key: ''
    
  elasticsearch:
    enabled: true
    url: ''

keycloak:
  replicas: 1
  extraEnv: |
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  fullnameOverride: keycloak
  ingress:
    enabled: false
  postgresql:
    fullnameOverride: "keycloak-postgresql"
    persistence:
      enabled: true
      existingClaim: "keycloak-postgresql-data"
