ingress:
  enabled: true


# allow cors and set the allowed methods and allow set proxy headers so keycloak could be looged in from different domain
ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      default-ssl-certificate: tensorleap/tls-secret
    image:
      digest: ''
    config:
      enable-snippets: "true"
      allow-snippet-annotations: "true"
      enable-cors: "true"
      cors-allow-origin: "*"
      cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
      cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
      cors-expose-headers: "Content-Length,Content-Range"
    admissionWebhooks:
      patch:
        image:
          digest: ''

global:
  target_namespace: ''
  storageClassName: ''
  create_local_volumes: true
  domain: 'localhost'
  basePath: ''
  url: 'http://localhost'
  tls:
    enabled: false
    cert: ''
    key: ''
    
  elasticsearch:
    enabled: true
    url: ''

keycloak:
  replicas: 1
  extraEnv: |
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  fullnameOverride: keycloak
  ingress:
    enabled: false
  postgresql:
    fullnameOverride: "keycloak-postgresql"
    persistence:
      enabled: true
      existingClaim: "keycloak-postgresql-data"
  pgchecker:
    image:
      repository: docker.io/library/busybox # must to add the library before the image name for air-gapped environments
datadog:
  enabled: true
  clusterAgent:
    enabled: false
  datadog:
    processAgent:
      enabled: false
    tags:
      - "env:on-prem"
    logs:
      enabled: true
      containerCollectAll: false
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    site: datadoghq.com
