ingress:
  enabled: true

ingress-nginx:
  enabled: true
  fullnameOverride: ingress-nginx
  controller:
    image:
      digest: ''
    admissionWebhooks:
      patch:
        image:
          digest: ''

global:
  target_namespace: ''
  storageClassName: ''
  create_local_volumes: true
  elasticsearch:
    enabled: true
    url: ''

keycloak:
  replicas: 1
  extraEnv: |
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin
  fullnameOverride: keycloak
  ingress:
    enabled: false
  postgresql:
    fullnameOverride: "keycloak-postgresql"
