ingress-nginx:
  fullnameOverride: ingress-nginx

kibana:
  fullnameOverride: kibana
  healthCheckPath: /kibana/app/kibana
  image: us-central1-docker.pkg.dev/tensorleap/main/kibanimat
  imageTag: master-ef30f279-stable
  kibanaConfig:
    kibana.yml: |
      server:
        basePath: /kibana
        rewriteBasePath: true
  elasticsearchHosts: http://elasticsearch-master:9200

minio:
  mode: standalone
  existingSecret: minio-secret
  service:
    type: NodePort
  securityContext:
    enabled: false
  persistence:
    size: 2Gi
    VolumeName: minio-data
  resources:
    requests:
      memory: 500Mi
  buckets:
    - name: session
      policy: public
