ingress-nginx:
  fullnameOverride: ingress-nginx

kibana:
  fullnameOverride: kibana
  healthCheckPath: /kibana/app/kibana
  image: gcr.io/tensorleap/kibanimat
  imageTag: master-f8556951-stable
  kibanaConfig:
    kibana.yml: |
      server:
        basePath: /kibana
        rewriteBasePath: true
  elasticsearchHosts: http://elasticsearch-master:9200

rabbitmq:
  fullnameOverride: rabbitmq
  auth:
    user: user
    password: 3e3abae2-6325-11ec-90d6-0242ac120003
    erlangCookie: 3e3abae2-6325-11ec-90d6-0242ac120003
  persistence:
    size: 500Mi

minio:
  mode: standalone
  existingSecret: minio-secret
  service:
    type: NodePort
  securityContext:
    enabled: false
  persistence:
    size: 2Gi
    VolumeName: minio-data
  resources:
    requests:
      memory: 500Mi
  buckets:
    - name: session
      policy: public
