{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tensorleap-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1500m
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: tensorleap-node-server
                port:
                  name: http
            path: /api
            pathType: ImplementationSpecific
          - backend:
              service:
                name: tensorleap-node-server
                port:
                  name: http
            path: /socket.io
            pathType: ImplementationSpecific
{{ end }}
