{{ if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-common-scripts
  labels:
    app: mongodb
data:
  is_ready.sh: |
    #!/bin/bash
    mongosh --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
  ping.sh: |
    #!/bin/bash
    mongosh --eval 'db.adminCommand("ping")'
  entrypoint.sh: |
    #!/bin/bash

    mkdir -p $MONGO_DB_PATH
    chmod 777 $MONGO_DB_PATH

    exec mongod --bind_ip_all --dbpath $MONGO_DB_PATH
{{ end }}
