apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-server-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-server-role
subjects:
  - kind: ServiceAccount
    name: node-server-sa
    namespace: {{ .Release.Namespace }}
