name: Release Airgap Pack
on:
  workflow_dispatch:
    inputs:
      manifest_name:
        description: "Name of the manifest (use curent branch name if not provided)"
        required: false

jobs:
  build:
    runs-on: ubuntu-32-cores
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Check format
        run: make check-fmt

      - name: Get tensorleap chart version
        id: get_tensorleap_chart_version
        # Create output that contains the version from charts/tensorleap/Chart.yaml
        run: |
          echo "version=$(cat charts/tensorleap/Chart.yaml | grep -E '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Save mainifest version
        id: save_manifest_version
        env:
          MANIFEST_NAME: ${{ inputs.manifest_name || format('manifest-{0}', steps.get_tensorleap_chart_version.outputs.version) }}
        run: echo "manifest=${{ env.MANIFEST_NAME }}" >> $GITHUB_OUTPUT

      - name: Build Airgap Pack
        run: go run . pack -o pack.tar.gz --tag ${{ steps.save_manifest_version.outputs.manifest }}

      - name: Upload Airgap Pack to S3
        run: |
          aws s3 cp pack.tar.gz s3://tensorleap-assets/airgap-versions/tl-${{ steps.save_manifest_version.outputs.manifest }}-linux-amd64-.tar.gz
