name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Switch to index branch
        run: git checkout index

      - name: Update files
        run: |
          git checkout master -- install.sh

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update static files"
          
      - name: Switch to master branch
        run: git checkout master

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0

        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PAGES_BRANCH: index

  release-installation-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Get tensorleap chart version
        id: get_tensorleap_chart_version
        # Create output that contains the version from charts/tensorleap/Chart.yaml
        run: |
          echo "version=$(cat charts/tensorleap/Chart.yaml | grep -E '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Create installation manifest
        run: |
          go run . create-manifest --tensorleap-chart-version ${{ steps.get_tensorleap_chart_version.outputs.version }} --output manifest.yaml

      - name: Print chart versions
        run: |
          echo "Tensorleap chart version ${{ steps.get_tensorleap_chart_version.outputs.version }}"

      - name: Print manifest
        run: cat manifest.yaml

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "manifest.yaml"
          tag: "manifest-${{ steps.get_tensorleap_chart_version.outputs.version }}"
          skipIfReleaseExists: true
          generateReleaseNotes: true
